[[plugins]]
package = "@algolia/netlify-plugin-crawler"
[plugins.inputs]
branches = ['production']
#default:
disabled = false
# pathPrefix = ""
# customDomain = "flarehub.io"
#default:
renderJavaScript = false
# template = "hierarchical"
[[headers]]
for = "/img/*"
[headers.values]
Cache-Control = "public, s-max-age=172800"
