[[plugins]]
  package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
    branches = ['production']
    #default:
    disabled = false
    # pathPrefix = ""
    # customDomain = "flarehub.io"
    #default:
    renderJavaScript = false
# template = "hierarchical"
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
    # Path to the sitemap URL
    sitemapPath = "/sitemap.xml"
    # Enabled providers to submit sitemap to. Possible providers are currently only 'google', 'bing', 'yandex'.
    providers = ["google", "bing"]
[[plugins]]
  package = "netlify-plugin-csp-generator"
  [plugins.inputs]
    buildDir = "out"
    [plugins.inputs.policies]
      defaultSrc = "'self'"
      fontSrc = "'self' data:"
      styleSrc = "'self' 'unsafe-inline' flarehub.containers.piwik.pro"
      img-src = "'self' 'unsafe-inline' data: blob: *.flarehub.io flarehub.piwik.pro flarehub.containers.piwik.pro www.google-analytics.com"
      scriptSrc = "'self' 'unsafe-inline' 'strict-dynamic' flarehub.containers.piwik.pro www.google-analytics.com identity.netlify.com"
      connectSrc = "'self' flarehub.piwik.pro flarehub.containers.piwik.pro www.google-analytics.com *.algolia.net *.algolianet.com *.flarehub.io"
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Content-Security-Policy = '''
      default-src 'self';
      font-src 'self' data:;
      style-src 'self' 'unsafe-inline';
      img-src 'self' 'unsafe-inline' data: blob: *.netlify.app *.flarehub.io;
      script-src 'self' 'unsafe-eval';
      connect-src 'self' blob: https://www.netlifystatus.com *.netlify.app *.flarehub.io *.s3.amazonaws.com;'''
[context.branch-deploy]
  environment = { PIWIK_TAG_ID = "1379a89d-fd09-4a99-b62a-25455447ef1e" }
[context.deploy-preview]
  environment = { PIWIK_TAG_ID = "1379a89d-fd09-4a99-b62a-25455447ef1e" }
