[[plugins]]
package = "@algolia/netlify-plugin-crawler"
[plugins.inputs]
branches = ['production']
disabled = false
pathPrefix = "/insights"
# customDomain = "flarehub.io"
renderJavaScript = false
template = "hierarchical"
